Repository GSG-G11/Amjad-Abdulrahman-Quran-app, pull requests merged in 2022-02, with the labels that each got.

#2 create file structure
  .gitignore
  index.html
  js/main.js
  js/test.js
  package.json
  style.css
Labels: Done

#6 create main section and styling this
  assets/background.jpg
  index.html
  style.css
Labels: Done

#7 3 header section
  index.html
  js/main.js
  style.css
Labels: Approve

#12 create fetch function and render dom in html
  index.html
  js/logic.js
  js/main.js
Labels: Approve

#15 add ayah change automatically
  index.html
  js/logic.js
  js/main.js
Labels: Awaiting Review

#17 create play-pause functionality and render msg error
  js/logic.js
  js/main.js
  style.css
Labels: Approve

#19 add random surah functionallity
  index.html
  js/logic.js
  js/main.js
  style.css
Labels: Approve

#25 20 date time
  index.html
  js/logic.js
  js/main.js
  style.css
Labels: Awaiting Review

#30 28 next previous ayah
  js/logic.js
  js/main.js
Labels: Approve

#31 add icon to browser tap
  assets/koran.png
  index.html
  style.css
Labels: Awaiting Review

#32 add surah name trans and modify styling fot media quries
  index.html
  js/logic.js
  js/main.js
  style.css
Labels: Awaiting Review

#34 add random background feature
  index.html
  js/logic.js
  js/main.js
  style.css
Labels: Approve

#35 fix playBtn
  js/main.js
  style.css
Labels: Awaiting Review

#38 fixed header-footer-responsitivity
  index.html
  style.css
Labels: Done

#43 add testing for date and time funcs
  js/logic.js
  js/test.js
Labels: Awaiting Review

#45 fix play-pause-icon doesn't change on next-back click
  js/logic.js
  js/main.js
Labels: Approve

#48 add a fallback background-image
  README.md
  js/logic.js
  style.css
Labels: Approve
